# Site
name: "i8 Terminal blog"
title: "i8 Terminal blog"
description: "Modern Market Research with the Power of Command-Line"
logo: 'assets/images/i8terminal.png'
favicon: 'assets/images/favicon.png'
domain: investoreight.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://investoreight.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /i8-terminal-blog     # place folder name if the site is served in a subfolder
google_analytics: ''
disqus: ''
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  i8 terminal:
    name: i8 terminal
    display_name: i8 terminal
    avatar: "assets/images/i8terminal_avatar.jpg"
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: info@investoreight.com
    web: https://i8terminal.io/
    twitter: https://twitter.com/i8terminal
    description: "Modern Market Research with the Power of Command-Line"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
